# This will build the BCV repo and upload the package as an artifact

name: Modified Build BCV
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - '8'
        - '11'
        - '17'
        - '21'
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-build (${{ matrix.java }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/bytecode-viewer/bytecode-viewer', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v4
    - run: touch optcd-3.txt
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: maven
    - run: touch optcd-4.txt
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: touch optcd-5.txt
    - name: Extract Maven project version
      run: echo "bcv_version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}'
        --non-recursive exec:exec)" >> $GITHUB_ENV
      id: project
    - run: touch optcd-6.txt
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Bytecode-Viewer-${{ env.bcv_version }}-SNAPSHOT
        path: target/Bytecode-Viewer-${{ env.bcv_version }}.jar
        retention-days: 90
    - run: touch optcd-7.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-build (${{ matrix.java }})
        path: /home/runner/inotifywait-log-build (${{ matrix.java }}).csv
    name: build (${{ matrix.java }})
'on':
- push
- workflow_dispatch
